In [1]:
import numpy as np

data=np.loadtxt('training_boston_x_y_train.csv',delimiter=",")
data

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [2]:
x_train=data[:,:13]
x_train

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [3]:
from sklearn import preprocessing
sq=[]
for i in x_train:
    sq.append(i**2)
sq=np.array(sq)
x_train=np.append(x_train, sq, axis=1)

scaler=preprocessing.StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_train.shape

(379, 26)

In [4]:
y_train=data[:,13]
y_train.shape

(379,)

In [5]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(x_train,y_train)

GradientBoostingRegressor()

In [6]:
data2=np.loadtxt('test_boston_x_test.csv',delimiter=",")
x_test=data2
x_test.shape

(127, 13)

In [7]:
sq=[]
for i in x_test:
    sq.append(i**2)
sq=np.array(sq)
x_test=np.append(x_test, sq, axis=1)

scaler=preprocessing.StandardScaler()
scaler.fit(x_test)
x_test=scaler.transform(x_test)
x_test.shape

(127, 26)

In [8]:
y_pred = model.predict(x_test)
y_pred

array([10.66987087, 27.38631592, 23.33102818, 23.64557325, 20.95829987,
       21.29394593, 25.88813172, 27.37973602, 20.94264528, 23.75837557,
       22.73893105, 21.17098686, 21.24766881, 21.61658242, 48.9577193 ,
       22.96757794, 24.13882258, 24.01097827, 20.25916804, 32.61744238,
       22.13418318, 21.84172233, 39.30785897, 32.52160228, 34.46126671,
       17.7867608 , 19.69459839, 29.73693795, 19.84695024, 27.36736205,
       19.29967674, 24.24841791, 24.88523782, 23.86539784, 13.3829787 ,
       23.78743791, 23.51966989, 20.1391323 , 23.2805643 ,  7.53702396,
       12.77783896, 25.22147856, 26.122706  , 21.58017325, 22.46260729,
       11.42769089, 41.37424696, 26.00523158, 34.03725176, 10.63660422,
       12.48866059, 44.82776208, 12.13990535, 22.0677279 , 18.04033611,
       20.4412471 , 19.93126443, 23.89223328, 17.53563984, 14.50062927,
       13.06439279, 30.65777061, 22.47702192, 22.70972851, 15.2181358 ,
       15.35584912, 27.37919158, 12.97707345, 21.53082039, 21.99

In [9]:
for i in range(len(y_pred)):
    y_pred[i]=round(y_pred[i],5)
y_pred

array([10.66987, 27.38632, 23.33103, 23.64557, 20.9583 , 21.29395,
       25.88813, 27.37974, 20.94265, 23.75838, 22.73893, 21.17099,
       21.24767, 21.61658, 48.95772, 22.96758, 24.13882, 24.01098,
       20.25917, 32.61744, 22.13418, 21.84172, 39.30786, 32.5216 ,
       34.46127, 17.78676, 19.6946 , 29.73694, 19.84695, 27.36736,
       19.29968, 24.24842, 24.88524, 23.8654 , 13.38298, 23.78744,
       23.51967, 20.13913, 23.28056,  7.53702, 12.77784, 25.22148,
       26.12271, 21.58017, 22.46261, 11.42769, 41.37425, 26.00523,
       34.03725, 10.6366 , 12.48866, 44.82776, 12.13991, 22.06773,
       18.04034, 20.44125, 19.93126, 23.89223, 17.53564, 14.50063,
       13.06439, 30.65777, 22.47702, 22.70973, 15.21814, 15.35585,
       27.37919, 12.97707, 21.53082, 21.99896, 27.31175, 22.70742,
       20.54252,  7.85026, 39.75661, 22.25061, 27.63067, 23.98383,
       13.34893, 33.32681, 20.53179, 22.04325, 20.93868, 18.63267,
       16.93723, 35.70624, 26.47131,  7.86553, 20.27122, 16.69

In [10]:
np.savetxt('Prediction.csv',y_pred,delimiter=',')
import pandas as pd
df=pd.read_csv('Prediction.csv')
df.rename(columns={0:'predictions'},inplace=True)
df.to_csv('Prediction_final.csv',index=False)